Repository econia-labs/testnet-dashboard, pull requests merged in 2023-10, with the labels that each got.

#13 [ECO-541] - Loading page animation
  components/layout.tsx
  components/loader.tsx
  pages/_app.tsx
  styles/loader.css
  tailwind.config.ts
Labels: enhancement

#17 [ECO-586] - Fix Econia logo onClick
  components/layout.tsx
  components/loader.tsx
  components/navbar.tsx
  package-lock.json
Labels: bug

#18 [ECO-583] Fix intro text glitch
  components/loader.tsx
Labels: bug

#19 [Eco 584] Fix countdown number glitch
  components/count-down.tsx
Labels: bug

#20 [ECO-594] - Update confetti colors
  components/confetti-effect/index.tsx
Labels: help wanted

#21 [ECO-589] Fix menu open state when narrowing down screens
  components/navbar.tsx
  package-lock.json
Labels: bug

#22 [ECO-590] Update leaderboard infinite roll
  components/leaderboard-table.tsx
  containers/leaderboard/index.tsx
Labels: bug

#23 [ECO-608] Update trade partners logos
  icons/aries-logo.svg
  icons/gator-logo.svg
  icons/kana-logo.svg
Labels: bug

#24 [ECO-604] - fix icon color, wallet icons and remove fewcha wallet
  connect-wallet/provider.tsx
  connect-wallet/wallet-buttons.tsx
  icons/arrow-right-icon.tsx
  icons/martian-icon.tsx
  icons/petra-icon.tsx
  icons/pontem-icon.tsx
  icons/rise-icon.tsx
Labels: help wanted

#25 [ECO-607] Update connect wallet button style
  connect-wallet/connect-wallet-button.tsx
  connect-wallet/connection-button.tsx
  connect-wallet/disconnect-wallet-button.tsx
  connect-wallet/disconnect-wallet-modal-body.tsx
  containers/leaderboard/index.tsx
Labels: bug

#26 [ECO-598] Fix intro animation bug
  components/loader.tsx
Labels: bug

#29 [ECO-617] Update connect wallet button text font
  connect-wallet/connection-button.tsx
Labels: bug

#30 [ECO-633] Update favicon
  public/favicon.ico
Labels: bug

#31 [ECO-656] Update Aries market link
  components/partner-card.tsx
  containers/trade/index.tsx
  types/partner.ts
Labels: enhancement

#32 [ECO-513] Integrate leaderboard API
  components/count-down.tsx
  components/leaderboard-stats.tsx
  components/leaderboard-table.tsx
  containers/leaderboard/index.tsx
  package-lock.json
  package.json
  services/axiosSetup.ts
  services/index.ts
  services/leaderboard.service.ts
  styles/globals.css
  types/leaderboard.ts
Labels: enhancement

#33 [ECO-654] Add env example and update readme file
  .env.example
  README.md
Labels: enhancement

#34 [ECO-677] - Fix confetti animation
  components/navbar.tsx
  connect-wallet/wallet-buttons.tsx
Labels: bug

#35 Update api service config
  .env.example
  components/count-down.tsx
  containers/leaderboard/index.tsx
  services/axiosSetup.ts
  services/leaderboard.service.ts
Labels: enhancement

#38 [ECO-691] - Update link to rules
  components/navbar.tsx
Labels: enhancement

#39 [ECO-632] - Add fade into view effect for econia logo
  components/loader.tsx
Labels: enhancement

#41 [ECO-632] - Change animation duration
  components/loader.tsx
Labels: enhancement

#43 [ECO-701] - Add hover effect to trader addresses
  components/leaderboard/user-row.tsx
Labels: enhancement

#42 [ECO-703] - Update queries
  components/leaderboard/leaderboard-stats.tsx
  components/leaderboard/leaderboard-table.tsx
  components/leaderboard/user-row.tsx
  containers/leaderboard/index.tsx
  services/axiosSetup.ts
  services/leaderboard.service.ts
  types/leaderboard.ts
Labels: enhancement

#44 [ECO-700] - Add loading screen while fetching data
  components/leaderboard/fetch-loader.tsx
  components/leaderboard/leaderboard-table.tsx
  containers/leaderboard/index.tsx
  pages/_app.tsx
  services/leaderboard.service.ts
  styles/fetch-loader.css
Labels: enhancement

#45 [ECO-723] - Fix bug on user connection address with no trading history
  components/leaderboard/leaderboard-table.tsx
Labels: bug

#48 [ECO-721] - Change default page from trade to leaderboard
  components/navbar.tsx
  pages/index.tsx
  pages/leaderboard/index.tsx
  pages/trade/index.tsx
Labels: enhancement

#52 [ECO-722] - Fix leaderboard UI on extra small mobile screen
  components/leaderboard/leaderboard-table.tsx
  components/leaderboard/user-row.tsx
  containers/leaderboard/index.tsx
  styles/globals.css
Labels: bug

#54 [ECO-700] - Update skeleton loading
  components/leaderboard/count-down.tsx
  components/leaderboard/leaderboard-stats.tsx
  components/leaderboard/leaderboard-table.tsx
  components/leaderboard/loading-table.tsx
  components/loader.tsx
  containers/leaderboard/index.tsx
  package-lock.json
  package.json
  pages/_app.tsx
Labels: enhancement

#55 [ECO-702] - Handle case connected wallet not eligible
  components/leaderboard/leaderboard-table.tsx
  services/leaderboard.service.ts
Labels: enhancement

#56 [ECO-725] - Update max width for partner logos
  containers/leaderboard/index.tsx
  containers/trade/index.tsx
Labels: bug

#57 [ECO-743] - Center navbar links
  components/navbar.tsx
  services/axiosSetup.ts
Labels: bug

#58 [ECO-733] - Handle leading zero address case
  components/leaderboard/leaderboard-table.tsx
  connect-wallet/disconnect-wallet-modal-body.tsx
  containers/leaderboard/index.tsx
  utils/address-utils.ts
Labels: enhancement

#59 [ECO-736] - Handle case logged in user in top 5 display
  components/leaderboard/leaderboard-table.tsx
Labels: enhancement

#63 [ECO-744] - Update swapGPT logo
  containers/trade/index.tsx
  partner-logos/partner-3.png
  partner-logos/partner-3.svg
Labels: enhancement

#64 [ECO-743] - Remove arrow icon on navbar rules
  components/navbar.tsx
  icons/arrow-external-right-icon.tsx
  package-lock.json
Labels: enhancement

#65 [ECO-755] - Fix grain effect
  styles/heart.css
Labels: bug

#67 [ECO-750] - Lock table header row during scroll
  components/leaderboard/leaderboard-table.tsx
  components/loader.tsx
  containers/leaderboard/index.tsx
Labels: enhancement

#69 [ECO-751] - Highlight logged in user's row
  components/leaderboard/leaderboard-table.tsx
Labels: enhancement

#68 [ECO-756] - Fix scroll bug when menu open
  components/navbar.tsx
Labels: bug

#74 [ECO-751] - Fix logged in user row background
  components/leaderboard/leaderboard-table.tsx
Labels: bug

#75 [ECO-749] - Add competition ID to queries
  services/leaderboard.service.ts
Labels: enhancement

#76 [ECO-766] - Combine volume and metadata queries into one
  containers/leaderboard/index.tsx
  services/leaderboard.service.ts
  types/leaderboard.ts
Labels: enhancement

#79 [ECO-761] - Round volume and points column values
  components/leaderboard/user-row.tsx
Labels: enhancement

#82 [ECO-773] - Fix mobile column mismatch
  components/leaderboard/user-row.tsx
Labels: bug

#83 [ECO-778] - Include decimal points for volume
  components/leaderboard/user-row.tsx
Labels: enhancement

#86 [ECO-784] - Always show 2 decimals for volume values
  components/leaderboard/leaderboard-stats.tsx
  components/leaderboard/user-row.tsx
Labels: enhancement

#87 [ECO-771] - Update global loader show condition
  components/layout.tsx
Labels: enhancement

#88 [ECO-771] - Fix loader's condition
  components/layout.tsx
Labels: bug

#91 [ECO-793] - Optimize polling queries
  .env.example
  components/leaderboard/leaderboard-table.tsx
  containers/leaderboard/index.tsx
  services/leaderboard.service.ts
Labels: enhancement

#93 [ECO-791] - Implement rate limiting message
  components/error-screen/index.tsx
  components/maintenance/index.tsx
  constants/error-messages.ts
  containers/leaderboard/index.tsx
  services/index.ts
Labels: enhancement

#96 [ECO-806] - Fix leaderboard mobile view
  components/leaderboard/leaderboard-table.tsx
  components/leaderboard/user-row.tsx
  components/navbar.tsx
  containers/leaderboard/index.tsx
  tailwind.config.ts
Labels: bug

#97 [ECO-807] - Reduce font size to 18px if value too long
  components/leaderboard/leaderboard-stats.tsx
Labels: enhancement
